### ISSUE TITLE
ActiveRecord::UnknownAttributeError (unknown attribute 'create_as_active' for Import.):

### ISSUE THREAD

**Issue by deschmit** [seven1m/onebody#702] opened 2018-01-06 23:21 UTC
I'm testing out the software for the first time.  I've been able to manually setup a few members in the directory but now I'd like to test the import feature.  I get these errors in /var/log/onebody/production.log when doing an import

F, [2018-01-06T09:16:11.612264 #25246] FATAL -- :
ActiveRecord::UnknownAttributeError (unknown attribute 'create_as_active' for Import.):
  app/controllers/administration/imports_controller.rb:28:in `create'

I'm of wondering if I'm missing a setting for some option.  Maybe something like "Can Sign In?"  Your documentation shows a different page than what I see.  I don't have the check boxes on my import page.  Not sure if this is the root of my problem or if the documentation is just for an older version of the software.

**Comment by seven1m** [comment] 2018-09-30 11:58
I cannot reproduce this. The attribute does indeed exist, provided by the 'flag_shih_tzu' gem. Perhaps the database migration for adding the corresponding 'flags' column didn't run or your app didn't get restarted after an upgrade. I'm closing, but we can reopen if you want to troubleshoot some more. (Sorry, I know 10 months to respond to an issue is horrible; I didn't see this issue originally)

**Closed by seven1m** 2018-09-30 11:58 UTC
Labels: bug
